return {
  -- {
  --   'yetone/avante.nvim',
  --   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  --   -- ⚠️ must add this setting! ! !
  --   build = vim.fn.has 'win32' ~= 0 and 'powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false' or 'make',
  --   event = 'VeryLazy',
  --   version = false, -- Never set this value to "*"! Never!
  --   ---@module 'avante'
  --   ---@type avante.Config
  --   opts = {
  --     -- add any opts here
  --     -- this file can contain specific instructions for your project
  --     instructions_file = 'avante.md',
  --     -- for example
  --     provider = 'copilot',
  --     providers = {
  --       copilot = {
  --         model = 'GPT-5', -- Default model
  --       },
  --     },
  --   },
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --     'MunifTanjim/nui.nvim',
  --     --- The below dependencies are optional,
  --     'nvim-mini/mini.pick', -- for file_selector provider mini.pick
  --     'nvim-telescope/telescope.nvim', -- for file_selector provider telescope
  --     'hrsh7th/nvim-cmp', -- autocompletion for avante commands and mentions
  --     'ibhagwan/fzf-lua', -- for file_selector provider fzf
  --     'stevearc/dressing.nvim', -- for input provider dressing
  --     'folke/snacks.nvim', -- for input provider snacks
  --     'nvim-tree/nvim-web-devicons', -- or echasnovski/mini.icons
  --     'zbirenbaum/copilot.lua', -- for providers='copilot'
  --     {
  --       -- support for image pasting
  --       'HakonHarnes/img-clip.nvim',
  --       event = 'VeryLazy',
  --       opts = {
  --         -- recommended settings
  --         default = {
  --           embed_image_as_base64 = false,
  --           prompt_for_file_name = false,
  --           drag_and_drop = {
  --             insert_mode = true,
  --           },
  --           -- required for Windows users
  --           use_absolute_path = true,
  --         },
  --       },
  --     },
  --     {
  --       -- Make sure to set this up properly if you have lazy=true
  --       'MeanderingProgrammer/render-markdown.nvim',
  --       opts = {
  --         file_types = { 'markdown', 'Avante' },
  --       },
  --       ft = { 'markdown', 'Avante' },
  --     },
  --   },
  -- },
}

-- {
--   'yetone/avante.nvim',
--   event = 'VeryLazy',
--   lazy = false,
--   version = false, -- Use "*" for latest release, or false for latest code.
--   opts = {
--     provider = 'copilot',
--     providers = {
--       copilot = {
--         model = 'claude-3.7-sonnet', -- Default model
--       },
--     },
--   },
--   build = 'make',
--   dependencies = {
--     'nvim-treesitter/nvim-treesitter',
--     'stevearc/dressing.nvim',
--     'nvim-lua/plenary.nvim',
--     'MunifTanjim/nui.nvim',
--     'nvim-tree/nvim-web-devicons',
--     'zbirenbaum/copilot.lua',
--     {
--       'HakonHarnes/img-clip.nvim',
--       event = 'VeryLazy',
--       opts = {
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = { insert_mode = true },
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       'MeanderingProgrammer/render-markdown.nvim',
--       opts = {
--         file_types = { 'markdown', 'Avante' },
--       },
--       ft = { 'markdown', 'Avante' },
--     },
--   },
--   config = function(_, opts)
--     local available_models = {
--       ['claude-4-sonnet'] = { model = 'claude-4-sonnet' },
--       ['claude-3.7-sonnet'] = { model = 'claude-3.7-sonnet' },
--       ['claude-3.7-sonnet🙅‍♂️🛠️'] = { model = 'claude-3.7-sonnet', disable_tools = true },
--       ['claude-3.5-sonnet'] = { model = 'claude-3.5-sonnet' },
--       ['o3-mini-high'] = { model = 'o3-mini', reasoning_effort = 'high' },
--       ['o4-mini-high'] = { model = 'o4-mini', reasoning_effort = 'high' },
--       ['o4-mini-high🙅‍♂️🛠️'] = { model = 'o4-mini', reasoning_effort = 'high', disable_tools = true },
--       ['o3-mini'] = { model = 'o3-mini' },
--       ['o4-mini'] = { model = 'o4-mini' },
--       ['4o'] = { model = 'gpt-4o' },
--       ['4.1'] = { model = 'gpt-4.1' },
--       ['4.1🙅‍♂️🛠️'] = { model = 'gpt-4.1', disable_tools = true },
--       ['4.1-mini'] = { model = 'gpt-4.1-mini' },
--       ['gemini-2.5-pro'] = { model = 'gemini-2.5-pro' },
--       ['gemini-2.5-pro🙅‍♂️🛠️'] = { model = 'gemini-2.5-pro', disable_tools = true },
--       ['gemini-2.0-flash'] = { model = 'gemini-2.0-flash' },
--       ['o2'] = { model = 'o2' },
--       ['o3'] = { model = 'o3' },
--       ['o1'] = { model = 'o1', reasoning_effort = 'high' },
--     }
--
--     local function switch_model()
--       local model_keys = vim.tbl_keys(available_models)
--       vim.ui.select(model_keys, { prompt = 'Select Avante Model:' }, function(selected)
--         if selected then
--           opts.copilot = available_models[selected]
--           require('avante').setup(opts)
--           print('Switched Copilot model to: ' .. selected)
--         else
--           print 'Model selection canceled.'
--         end
--       end)
--     end
--
--     vim.keymap.set('n', '<leader>am', switch_model, { desc = 'Avante: Switch Copilot Model' })
--
--     require('avante').setup(opts)
--     print 'Avante.nvim configured. Use <leader>am to switch models at runtime.'
--   end,
-- },
-- }
